import { Component, OnInit } from '@angular/core';
import { IUser } from 'src/app/core/modeles/IUser';
import { Role } from 'src/app/core/modeles/Role';
import { TaskPriority } from 'src/app/core/modeles/TaskPriority';
import { TaskStatus } from 'src/app/core/modeles/TaskStatus';
import { Ticket } from 'src/app/core/modeles/Ticket';
import { TypeActivity } from 'src/app/core/modeles/TypeActivity';
import { RecentActivityUser } from 'src/app/core/modeles/RecentActivity';
import { IBadgeUser } from 'src/app/core/modeles/IBadgeUser';
import { Department } from 'src/app/core/modeles/Department';
import { UsersService } from 'src/app/core/services/users.service';
import { TicketService } from 'src/app/core/services/ticket.service';
import { HttpErrorResponse } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
})
export class DashboardComponent implements OnInit {
  favoriteTicketList: Ticket[] = [];
  // = [
  //   {
  //     id: 1,
  //     title: 'Ticket 1 test testtes ',
  //     type: {
  //       id: 1,
  //       label: 'Application',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Hight',
  //     status: TaskStatus.open,
  //     createdBy: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Mohamed',
  //       lastName: 'El Maghraoui',
  //       email: 'mohamed.elmaghraoui@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 2,
  //     // todo : add ... 3point apres un nombre de lettres
  //     title: 'Ticket 2 Ticket 2 Ticket 2 Ticket 2 Ticket 2 ',
  //     type: {
  //       id: 1,
  //       label: 'Achat',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Meduim',
  //     status: TaskStatus.inProgress,
  //     createdBy: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 3,
  //     title: 'Ticket 3',
  //     type: {
  //       id: 1,
  //       label: 'Incedent',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Low',
  //     status: TaskStatus.canceled,
  //     createdBy: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 3,
  //     title: 'Ticket 3',
  //     type: {
  //       id: 1,
  //       label: 'Incedent',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Low',
  //     status: TaskStatus.evaluating,
  //     createdBy: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 3,
  //     title: 'Ticket 3',
  //     type: {
  //       id: 1,
  //       label: 'Incedent',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Low',
  //     status: TaskStatus.resolved,
  //     createdBy: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 3,
  //     title: 'Ticket 3',
  //     type: {
  //       id: 1,
  //       label: 'Incedent',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Low',
  //     status: TaskStatus.rejected,
  //     createdBy: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  //   {
  //     id: 3,
  //     title: 'Ticket 3',
  //     type: {
  //       id: 1,
  //       label: 'Incedent',
  //       lien: '',
  //       description: '',
  //     },
  //     priority: 'Low',
  //     status: TaskStatus.testing,
  //     createdBy: {
  //       id: 2,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Ismail',
  //       lastName: 'Meggouri',
  //       email: 'ismail.meggouri@gmail.com',
  //       status: true,
  //       post: 'Back End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },
  //     createdTime: '11-05-2024',
  //     affectedTo: {
  //       id: 1,
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: '',
  //       phoneNumber: '',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //     },

  //     referenceTicket: '',
  //     description:
  //       'Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem ',
  //     sharedWith: [
  //       {
  //         id: 1,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Soufiane',
  //         lastName: 'El Maghraoui',
  //         email: 'soufiane.elmaghraoui@gmail.com',
  //         status: false,
  //         post: 'Front End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //       {
  //         id: 2,
  //         image:
  //           'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //         firstName: 'Ismail',
  //         lastName: 'Meggouri',
  //         email: 'ismail.meggouri@gmail.com',
  //         status: true,
  //         post: 'Back End Developer',
  //         department: '',
  //         phoneNumber: '',
  //         enabled: true,
  //         username: 's.elmaghraoui',
  //       },
  //     ],
  //     isFavorit: true,
  //   },
  // ];
  TaskStatus = TaskStatus;
  Activity = TypeActivity;
  Role = Role;
  roles: string[] = [];

  recentActivities: RecentActivityUser[] = [];
  // [
  //   {
  //     id: 1,
  //     idTicket: 1,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.changedStatus,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 2,
  //     idTicket: 2,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.createdTicket,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 3,
  //     idTicket: 3,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.sharedTicket,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 4,
  //     idTicket: 4,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.affectedTicket,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       enabled: true,
  //       username: 's.elmaghraoui',
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  //   {
  //     id: 5,
  //     idTicket: 5,
  //     referenceTicket: 'RFZ-5528',
  //     ativity: TypeActivity.addComment,
  //     author: {
  //       id: 1,
  //       referenceUser: 'SE-123456',
  //       image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
  //       firstName: 'Soufiane',
  //       lastName: 'El Maghraoui',
  //       email: 'soufiane.elmaghraoui@gmail.com',
  //       status: false,
  //       post: 'Front End Developer',
  //       department: 'Developpment',
  //       phoneNumber: '0635383046',
  //       username: 's.elmaghraoui',
  //       enabled: true,
  //       location: 'Casablnca , Sidi Maarouf',
  //       joinDate: '15-08-2023',
  //     },
  //     time: '12:05PM',
  //   },
  // ];
  departments: Department[] = [];

  helpDesk: IBadgeUser = {
    image: 'https://flowbite.com/docs/images/people/profile-picture-5.jpg',
    firstName: 'Mohamed',
    lastName: 'El Maghraoui',
  };

  constructor(
    private usersService: UsersService,
    private ticketService: TicketService
  ) {}

  ngOnInit(): void {
    this.roles = this.usersService.getRoles();
    if (this.roles.includes(Role.helpDesk) || this.roles.includes(Role.admin))
      this.getFavoriteTickets();
    else if (this.roles.includes(Role.user)) {
      // this.getTicketsForUser();
    }
  }

  getFavoriteTickets() {
    this.ticketService.getAllTickets().subscribe({
      next: (tickets: Ticket[]) => {
        tickets.forEach((ticket) => {
          if (ticket.favorite) this.favoriteTicketList = tickets;
        });
      },
      error: (error: HttpErrorResponse) => {
        console.log(error.message);
      },
    });
  }

  toggleFavorits(idTicket?: number) {
    this.favoriteTicketList.forEach((ticket: Ticket) => {
      if (ticket.id === idTicket) ticket.favorite = !ticket.favorite;
    });
  }
}
